name: GitHub Scripts Exit

on:
  push:
    branches:
      - main

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Github Scripts with exit code
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log('hello')
            throw 'error'
            console.log('world')
      - name: Github Scripts without exit code
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            console.log('hoge')
